version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 user_crud.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      PGDATABASE: railway
      PGHOST: viaduct.proxy.rlwy.net
      PGPASSWORD: JvEllUsOUOMFoSzJbjaGwWHMaMLjtGfd
      PGPORT: 20925
      PGUSER: postgres
    networks:
      - user_crud_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - user_crud_network

networks:
  user_crud_network:
    driver: bridge
